#!/usr/bin/env ruby
#
# create built-in class table.
#
#  Copyright (C) 2015- Kyushu Institute of Technology.
#  Copyright (C) 2015- Shimane IT Open-Innovation Center.
#
#  This file is distributed under BSD 3-Clause License.
#
# (usage)
# ruby make_class_table.rb [option] src_files...
#
#  -o output filename.
#  -v verbose
#

require "optparse"
require_relative "common_sub"


##
# verbose print
#
def vp( s, level = 1 )
  STDERR.puts s  if $opts[:v] >= level
end


##
# parse command line option
#
def get_options
  ret = {:v=>0}
  opt = OptionParser.new

  opt.banner = "Usage: #{File.basename($0)} [options] src_files..."
  opt.on("-o output file") {|v| ret[:out_file] = v }
  opt.on("-v", "--verbose", "verbose mode") {|v| ret[:v] += 1 }

  opt.parse!(ARGV)
  return ret

rescue OptionParser::MissingArgument =>ex
  STDERR.puts ex.message
  return nil
end


##
# read *.c file and extract classes
#
def fetch_builtin_classes( filename )
  ret = []
  vp("Process '#{filename}'")

  File.open( filename ) {|file|
    while src = get_method_table_source( file )
      param = parse_source_string( src )
      exit 1 if !param

      param[:classes].each {|cls1|
        ret << {
          :class => [ cls1[:class], cls1[:module] ].compact[0],
          :super => cls1[:super],
        }
      }
    end
  }

  return ret
end


##
# write builtin class table to file.
#
def write_file( all_classes )
  vp("Output file '#{$opts[:out_file] || "STDOUT"}'")
  begin
    file = $opts[:out_file] ? File.open( $opts[:out_file], "w" ) : $stdout
  rescue Errno::ENOENT
    puts "File can't open. #{output_filename}"
    exit 1
  end

  file.puts "/* Auto generated by make_class_table.rb */"
  file.puts "#ifndef MRBC_SRC_AUTOGEN_BUILTIN_CLASS_H_"
  file.puts "#define MRBC_SRC_AUTOGEN_BUILTIN_CLASS_H_"
  file.puts "
static const struct MRBC_BuiltinClass {
  mrbc_class *cls;
  mrbc_class *super;
} MRBC_BuiltinClass[] = {"

  all_classes.each {|cls1|
    cls_name = "MRBC_CLASS(#{cls1[:class]})"
    cls_super = cls1[:super] == "0" ? "0" : "MRBC_CLASS(#{cls1[:super]})"
    case cls1[:class]
    when "Float", "String", "Math"
      file.puts "#if MRBC_USE_#{cls1[:class].upcase}"
      file.puts "  { #{cls_name}, #{cls_super} },"
      file.puts "#endif"
    else
      file.puts "  { #{cls_name}, #{cls_super} },"
    end
  }
  file.puts "};"

  file.puts "#endif"
  file.close  if $opts[:out_file]
end


##
# main
#
$opts = get_options()
exit if !$opts

if ARGV.empty?
  STDERR.puts "File not given."
  exit 1
end

all_classes = []

ARGV.each {|filename|
  all_classes.concat( fetch_builtin_classes( filename ))
}

write_file( all_classes )

vp("Done")
