/* Auto generated by make_class_table.rb */
#ifndef MRBC_SRC_AUTOGEN_BUILTIN_CLASS_H_
#define MRBC_SRC_AUTOGEN_BUILTIN_CLASS_H_

static const struct MRBC_BuiltinClass {
  mrbc_class *cls;
  mrbc_class *super;
} MRBC_BuiltinClass[] = {
  { MRBC_CLASS(Object), 0 },
  { MRBC_CLASS(Proc), MRBC_CLASS(Object) },
  { MRBC_CLASS(NilClass), MRBC_CLASS(Object) },
  { MRBC_CLASS(TrueClass), MRBC_CLASS(Object) },
  { MRBC_CLASS(FalseClass), MRBC_CLASS(Object) },
  { MRBC_CLASS(Symbol), MRBC_CLASS(Object) },
  { MRBC_CLASS(Integer), MRBC_CLASS(Object) },
#if MRBC_USE_FLOAT
  { MRBC_CLASS(Float), MRBC_CLASS(Object) },
#endif
#if MRBC_USE_STRING
  { MRBC_CLASS(String), MRBC_CLASS(Object) },
#endif
  { MRBC_CLASS(Range), MRBC_CLASS(Object) },
  { MRBC_CLASS(Array), MRBC_CLASS(Object) },
  { MRBC_CLASS(Hash), MRBC_CLASS(Object) },
  { MRBC_CLASS(Exception), MRBC_CLASS(Object) },
  { MRBC_CLASS(NoMemoryError), MRBC_CLASS(Exception) },
  { MRBC_CLASS(NotImplementedError), MRBC_CLASS(Exception) },
  { MRBC_CLASS(StandardError), MRBC_CLASS(Exception) },
  { MRBC_CLASS(ArgumentError), MRBC_CLASS(StandardError) },
  { MRBC_CLASS(IndexError), MRBC_CLASS(StandardError) },
  { MRBC_CLASS(IOError), MRBC_CLASS(StandardError) },
  { MRBC_CLASS(NameError), MRBC_CLASS(StandardError) },
  { MRBC_CLASS(NoMethodError), MRBC_CLASS(NameError) },
  { MRBC_CLASS(RangeError), MRBC_CLASS(StandardError) },
  { MRBC_CLASS(RuntimeError), MRBC_CLASS(StandardError) },
  { MRBC_CLASS(TypeError), MRBC_CLASS(StandardError) },
  { MRBC_CLASS(ZeroDivisionError), MRBC_CLASS(StandardError) },
#if MRBC_USE_MATH
  { MRBC_CLASS(Math), 0 },
#endif
};
#endif
