/* Auto generated by make_method_table.rb */
#include "_autogen_builtin_symbol.h"

/*===== Module module =====*/
static const mrbc_sym method_symbols_Module[] = {
  MRBC_SYM(constants),
};

static const mrbc_func_t method_functions_Module[] = {
  c_module_constants,
};

struct RBuiltinClass mrbc_class_Module = {
  .sym_id = MRBC_SYM(Module),
  .flag_builtin = 1,
  .flag_module = 1,
  .num_builtin_method = sizeof(method_symbols_Module) / sizeof(mrbc_sym),
  .super = 0,
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "Module",
#endif
  .method_symbols = method_symbols_Module,
  .method_functions = method_functions_Module,
};
